spring:
  application:
    name: exam-system
  datasource:
    password: ${DB_PASSWORD:muzichuan26}
    username: ${DB_USERNAME:root}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:exam_system}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 3000ms
server:
  port: 7000
logging:
  level:
    web: trace
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.com.xuroot.entity
  configuration:
    map-underscore-to-camel-case: true
